@startuml
skinparam linetype ortho
!include <C4/C4_Container>

'-------------- Icons Area --------------
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/sqllite.puml
!includeurl ICONURL/devicons/javascript.puml
!includeurl ICONURL/devicons/nodejs.puml
!includeurl ICONURL/devicons2/react_original.puml
!includeurl ICONURL/devicons2/nodejs.puml
!includeurl ICONURL/devicons2/slack.puml
!includeurl ICONURL/devicons2/express_original.puml

'-------------- The Elements --------------
title: <size:30><&command> SlackBot Architecture <&command></size>

Person(user, "User")
DEV2_SLACK(slack, Slack, node, white) #c300ff

DEV2_REACT_ORIGINAL(webpanel, Web Panel, node, white) #00b503

Boundary(promobotBoundary, "") {

    DEV2_EXPRESS_ORIGINAL(slack_routes, Slack APIs, rectangle, white) #DeepSkyBlue
    Container(slackService, "Slack Services")
    Container(sessionService, "Session Services")
    Container(witService, "Conversation Services", "WIT")
    note bottom
        AI based conversation service
    end note

    DEV2_EXPRESS_ORIGINAL(webpanel_routes, WebPanel APIs, rectangle, white) #DeepSkyBlue
    DEV2_EXPRESS_ORIGINAL(general_routes, General APIs, rectangle, white) #DeepSkyBlue

    Boundary(entityServices, "") {
        DEV_NODEJS(teammateService, Teammate Services, rectangle, blue)
        DEV_NODEJS(supervisorService, Supervisor Services, rectangle, blue)
        DEV_NODEJS(roleService, Role Services, rectangle, blue)
    }
    DEV_SQLLITE(database,SQLite Database,database,red)

    Rel(slack_routes, slackService, "onMention / onMessage")
    Rel(slackService, sessionService, "get/set a Session")
    Rel(slackService, witService, "get a follow up answer")
    Rel(witService, entityServices, "CRUD")
    Rel(entityServices, database, "Queries")

    Rel(webpanel_routes, entityServices, "CRUD")
    Rel(general_routes, entityServices, "CRUD")

}

Rel(slack, slack_routes, "User Events")
Rel(slack_routes, slack, "Response Message")

Rel(webpanel, webpanel_routes, "Call APIs")
Rel(webpanel_routes, webpanel, "API Response")

Rel(webpanel, general_routes, "Call APIs")
Rel(general_routes, webpanel, "API Response")

user --> slack
user --> webpanel

@enduml
